### ISSUE TITLE
NoClassDefFoundError: org/apache/velocity/runtime/log/CommonsLogLogChute

### ISSUE THREAD

**Issue by mostcool** [alibaba/velocity-spring-boot-project#1]
Caused by: java.lang.NoClassDefFoundError: org/apache/velocity/runtime/log/CommonsLogLogChute
	at org.springframework.ui.velocity.VelocityEngineFactory.createVelocityEngine(VelocityEngineFactory.java:240)
	at org.springframework.web.servlet.view.velocity.VelocityConfigurer.afterPropertiesSet(VelocityConfigurer.java:121)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1692)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
	... 38 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.velocity.runtime.log.CommonsLogLogChute
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 common frames omitted

**Comment by mercyblitz** [comment]
It can't be found~
